baseURL = "https://demo.creativebulma.net/components/badge/1.0/"
languageCode = "en-us"
title = "BulmaBadge"
theme = "creativebulma"
[markup]
  [markup.highlight]
    style = "manni"

[menu]

  [[menu.main]]
    identifier = "how-to"
    name = "How-To"
    url = "#"
    weight = 20